### ISSUE TITLE
Failed to unseal vault

### ISSUE THREAD

**Issue by tzahimizrahi** [hashicorp/docker-vault#70] opened 2017-12-24 22:29 UTC
HI,
Vault failed to unseal, get an error:
failed to update entity in MemDB: alias "xxxxx-f6fd-6288-f715-yyyyyyy" in already tied to a different 

==> Vault server configuration:

                     Cgo: disabled
              Listener 1: tcp (addr: "0.0.0.0:8200", cluster address: "0.0.0.0:8201", tls: "enabled")
               Log Level:
                   Mlock: supported: true, enabled: true
                 Storage: mysql
                 Version: Vault v0.9.1
             Version Sha: 87b6919dea55da61d7cd444b2442cabb8ede8ab1

==> Vault server started! Log data will stream in below:

2017/12/24 22:20:21.950047 [INFO ] core: vault is unsealed
2017/12/24 22:20:21.950515 [INFO ] core: post-unseal setup starting
2017/12/24 22:20:21.950922 [INFO ] core: loaded wrapping token key
2017/12/24 22:20:21.950940 [INFO ] core: successfully setup plugin catalog: plugin-directory=
2017/12/24 22:20:21.951935 [INFO ] core: successfully mounted backend: type=generic path=secret/
2017/12/24 22:20:21.952073 [INFO ] core: successfully mounted backend: type=system path=sys/
2017/12/24 22:20:21.952593 [INFO ] core: successfully mounted backend: type=identity path=identity/
2017/12/24 22:20:21.952616 [INFO ] core: successfully mounted backend: type=cubbyhole path=cubbyhole/
2017/12/24 22:20:21.955337 [INFO ] expiration: restoring leases
2017/12/24 22:20:21.955431 [INFO ] rollback: starting rollback manager
2017/12/24 22:20:21.965934 [INFO ] core: pre-seal teardown starting
2017/12/24 22:20:21.965952 [INFO ] core: cluster listeners not running
2017/12/24 22:20:22.108049 [INFO ] rollback: stopping rollback manager
2017/12/24 22:20:22.108205 [INFO ] core: pre-seal teardown complete
2017/12/24 22:20:22.108273 [ERROR] core: post-unseal setup failed: error=failed to update entity in MemDB: alias "xxxxx-9937-8e3f-ab4e-xxxxx" in already tied to a different entity "yyyyyyy-0adc-a56a-7b4b-yyyyyyy"
2017/12/24 22:20:22.108313 [WARN ] core: vault is sealed

**Comment by jefferai** [comment] 2017-12-24 23:22
Duplicate of ML post.

**Closed by jefferai** 2017-12-24 23:22 UTC
