### ISSUE TITLE
Problem with wrapper docker container with versions 8+

### ISSUE THREAD

**Issue by matthewmrichter** [hashicorp/docker-vault#51] opened 2017-09-05 16:02 UTC
Hi,

We have a docker wrapper container for running Vault in our Mesosphere cluster. It's been working pretty well with Docker 0.7.x but when I change my dockerfile FROM to 0.8.0, or 0.8.1, the container does not start and does not provide any feedback as to why not. The container just stops right away. Docker logs does not show anything for the stopped container and there is no stdout/stderr output.

Dockerfile:
```
# Vault wrapper container to inject env variables, etc

FROM vault:0.8.1
MAINTAINER Motus DevOps

# Install curl and jq 
# (this is based on Alpine Linux - apk is the package manager)
RUN apk update
RUN apk add curl jq openssh

ADD vaultwrapper.sh /usr/local/bin/

ENTRYPOINT ["/usr/local/bin/vaultwrapper.sh"

```

vaultwrapper.sh:
```
#!/bin/sh
# Vault wrapper to set hostname/port in our marathon.

# If you have a borked vault znode
if [ -z "$VAULT_ZK_PATH" ]; then
    export VAULT_ZK_PATH="vault/"
    exit 1
fi

# Get instance ID using AWS's api.
INSTANCEID=`curl http://169.254.169.254/latest/meta-data/instance-id`

# Log level defaults to info
if [[ -z "$LOG_LEVEL" ]]; then
    LOG_LEVEL=info
fi

# Find the ZK string by querying Marathon
# We are passing the Marathon Master URL in via ansible.
ZK_URL=`curl -s -X GET $MARATHON_MASTER/v2/info | \
	jq --raw-output '.marathon_config.master' | \
	sed -e 's$zk://$$g' | sed -e 's$/mesos$$g'`

# Create a config file
# Note, we need to mount the certs at /etc/tls/.
CFG_FILE=$(mktemp)
cat > ${CFG_FILE} << EOF
backend "zookeeper" {
  address = "$ZK_URL"
  redirect_addr = "$VAULT_ADVERTISE_ADDR"
  cluster_addr = "$HOST:$PORT1"
  path = "$VAULT_ZK_PATH"
}

listener "tcp" {
  address = "0.0.0.0:8200"
  cluster_address = "0.0.0.0:8201"
  tls_cert_file = "/etc/tls/motusclouds_com.crt"
  tls_key_file = "/etc/tls/privkey.pem"
}

disable_mlock = true
EOF

# Call the vault executable now. Pass the configfile we just created and any other args.
/bin/vault server --log-level=$LOG_LEVEL -config=$CFG_FILE "$@"
```

I checked out https://github.com/hashicorp/docker-vault and the Dockerfile/entrypoint script appear to be the same except for the version. Is there something in the application that changed that would silently fail that changed between 0.7.3 and 0.8.0?

Thanks
Matt

**Comment by jefferai** [comment] 2017-09-05 16:03
Duplicate of https://groups.google.com/d/msg/vault-tool/ZR7kcN-yQMA/WrSU2t00AQAJ

**Closed by jefferai** 2017-09-05 16:03 UTC

**Comment by matthewmrichter** [comment] 2017-09-05 16:05
Would it be better to leave this ticket open for the purposes of tracking?

**Comment by jefferai** [comment] 2017-09-05 16:18
@matthewmrichter if you encounter errors with our official container, I'm happy to reopen it.
